package ch.empa.car;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CarReservationFormDesign extends VerticalLayout {
	protected DateTimeField takeOverDate;
	protected Button resetButton;

	public CarReservationFormDesign() {
		Design.read(this);
	}
}
